export const playlist = [
    {
      id: "1",
      artist: "Miles Davis",
      title: "Minnie",
      album: "The Complete On The Corner Sessions",
      avatarUrl: "https://bit.ly/code-beast",
      status: "active",
      role: "Senior Developer Advocate",
      rating: 4,
    },
    {
      id: "2",
      artist: "John Coltrane",
      title: "Naima",
      album: "Naima",
      avatarUrl: "https://bit.ly/kent-c-dodds",
      status: "active",
      role: "Director of DX",
      rating: 4,
    },
    {
      id: "3",
      artist: "Gangstarr",
      title: "Just to Get a Rep",
      album: "Step In The Arena",
      avatarUrl: "https://bit.ly/prosper-baba",
      status: "active",
      role: "Director of Evangelism",
      rating: 4,
    },
    {
      id: "4",
      artist: "Miles Davis",
      title: "One and One",
      album: "On The Corner",
      avatarUrl: "https://bit.ly/ryan-florence",
      status: "active",
      role: "Co-Founder",
      rating: 4,
    },
    {
      id: "5",
      artist: "Sun Ra",
      title: "Hour of Parting",
      album: "Sound Sun Pleasure",
      avatarUrl: "https://bit.ly/sage-adebayo",
      status: "active",
      role: "Frontend UI Engineer",
      rating: 4,
    },
  ];
  