import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ marginBottom: "50px" }}>
          <h1 className={styles.title}>
            Welcome to your <a href="https://nextjs.org">Vinyl Shopping List</a>
          </h1>
        </div>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>About &rarr;</h2>
            <p>Find out more about this application.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Vinyl List &rarr;</h2>
            <p>Get started editing your playlist now!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>See how others have used this tool.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://danielatochejuarez.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span>
            <Image src="/DajLogo3.png" alt="DAJ logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
